[meta]
name = "ManiaExchange Random Map Picker"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 124

version = "2.0.2"

[script]
imports = [ "Icons.as", "Permissions.as" ]
optional_dependencies = [ "ManiaExchange" ]

exports = [ "src/Exports/Exports.as" ]

timeout = 0