[meta]
name = "ManiaExchange Random Map Picker"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 124

version = "2.0.0"

[script]
imports = [ "Icons.as", "Permissions.as", "Dialogs.as" ]

defines = [ "MOCK_TAGS" ]