[meta]
name = "ManiaExchange Random Map Picker"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 124

version = "2.2.2"

[script]
imports = [ "Permissions.as" ]
optional_dependencies = [ "ManiaExchange", "ChaosMode", "NadeoServices" ]

exports = [ "src/Exports/Exports.as" ]

timeout = 0